version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/themes/ginpen-theme/
      - .backup:/var/wp-backup

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
      - .backup:/mnt/wp-backup

volumes:
  wordpress:
  db:
