version: '3'

services:

  wordpress:
    image: wordpress
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./.backup:/var/wp-backup
      - ./.volumes/wordpress:/var/www/html
      - ./ginpen-theme:/var/www/html/wp-content/themes/ginpen-theme/
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.backup:/mnt/wp-backup
      - ./.volumes/db:/var/lib/mysql
